### ISSUE TITLE
Jekyll 3 support

### ISSUE THREAD

**Issue by jiyeqian** [inukshuk/jekyll-scholar#84]
~/ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate jekyll-scholar-4.3.6, because jekyll-3.0.0.pre.beta6 conflicts with jekyll (~> 2.0) (Gem::ConflictError)

 from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
        from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems.rb:198:in `rescue in try_activate'
        from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems.rb:195:in `try_activate'
        from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/plugin_manager.rb:27:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/plugin_manager.rb:27:in `require_gems'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/site.rb:88:in `setup'

**Comment by inukshuk** [comment]
If you adjust the version constraint, you could test if scholar works with jekyll 3.0.

**Comment by jiyeqian** [comment]
I'm not familiar with Ruby. How to modify version constraint?

**Comment by inukshuk** [comment]
You need to fork this repository and change the constraint at:

https://github.com/inukshuk/jekyll-scholar/blob/master/jekyll-scholar.gemspec#L28

Then, in your Gemfile you require jekyll-scholar your fork instead of the original (using the `github` property in your Gemfile).

Otherwise you'll have to wait until someone else makes sure scholar works with version 3.

**Comment by jiyeqian** [comment]
I'm using the version 3, but jekyll-scholar would slow down the generation and cause the problem:

Liquid Exception: undefined method `resolve' for #<Liquid::Context:0x007f867341d150> in _posts/2014-10-20-multiple-classes.md

/Users/jiyeqian/.bundler/ruby/2.2.0/jekyll-scholar-5119d505d322/lib/jekyll/scholar/utilities.rb:446:in `block in keys': undefined method `resolve' for #<Liquid::Context:0x007fed7afb1e80> (NoMethodError)
        from /Users/jiyeqian/.bundler/ruby/2.2.0/jekyll-scholar-5119d505d322/lib/jekyll/scholar/utilities.rb:445:in `map'
        from /Users/jiyeqian/.bundler/ruby/2.2.0/jekyll-scholar-5119d505d322/lib/jekyll/scholar/utilities.rb:445:in `keys'
        from /Users/jiyeqian/.bundler/ruby/2.2.0/jekyll-scholar-5119d505d322/lib/jekyll/scholar/tags/cite.rb:20:in `render'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/block.rb:151:in `render_token'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/profiler.rb:80:in `profile_token_render'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/block.rb:135:in `block in render_all'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/block.rb:122:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/block.rb:122:in `render_all'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/block.rb:108:in `render'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/template.rb:210:in `block in render'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/template.rb:262:in `with_profiling'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/template.rb:209:in `render'
        from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.3/lib/liquid/template.rb:222:in `render!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/convertible.rb:112:in `render_liquid'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/convertible.rb:246:in `do_layout'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/post.rb:273:in `render'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/site.rb:170:in `block in render'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/site.rb:168:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/site.rb:168:in `render'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/site.rb:57:in `process'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/command.rb:28:in `process_site'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/commands/build.rb:60:in `build'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/commands/build.rb:35:in `process'
        from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta6/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /Users/jiyeqian/bin/jekyll:17:in `<main>'

Without `cite` tag in the Markdown file,  jekyll & liquid work well.

**Comment by mamoll** [comment]
This may be all that is needed to fix things for jekyll 3.0.0.pre.beta8 and liquid 3.0.6:
```
diff --git a/lib/jekyll/scholar/utilities.rb b/lib/jekyll/scholar/utilities.rb
index 15b3cd8..9867646 100644
--- a/lib/jekyll/scholar/utilities.rb
+++ b/lib/jekyll/scholar/utilities.rb
@@ -444,7 +444,7 @@ module Jekyll
         # We need to do this every time, to support for loops,
         # where the context can change for each invocation.
         Array(@keys).map do |key|
-          context.send(:resolve, key) || key
+          context[key] || key
         end
       end
 
@@ -452,7 +452,7 @@ module Jekyll
         return unless string
 
         string.gsub(/{{\s*([\w\.]+)\s*}}/) do |match|
-          context.send(:resolve, $1) || match
+          context[$1] || match
         end
       end
```

**Comment by inukshuk** [comment]
@mamoll yes this looks good!

All our tests are passing so I pushed version 5.0.0.pre.1 to RubyGems which you can use for further testing with the Jekyll 3 beta. If we don't run into any problems we can release 5.0.0 when Jekyll 3 is ready.

**Comment by jiyeqian** [comment]
This works good!

**Comment by jiyeqian** [comment]
I use jekyll 3.0.0.pre.beta8 and liquid 3.0.6.  There exists problems -- Liquid error.

My markdown source code: 

~~~html
本文根据Zdenek Kalal等人的论文“Tracking-Learning-Detection”{% cite kalal2012tracking %}意译而来。
~~~

I get this html code:
~~~html
本文根据Zdenek Kalal等人的论文“Tracking-Learning-Detection”Liquid error: undefined method `resolve’ for #<liquid::context:0x007fef3ad7c3d8>意译而来。</liquid::context:0x007fef3ad7c3d8>
~~~

**Comment by mamoll** [comment]
`resolve` is not used anywhere in the latest jekyll-scholar code. Make sure you have the 5.0.0.pre.1 prerelease.

**Comment by jiyeqian** [comment]
Thanks! It works OK now! I have corrected my Gemfile.

**Comment by inukshuk** [comment]
Jekyll 3 is out. All tests are green so I released version 5.0 just now -- fingers crossed. Thanks to @mamoll for making this happen.
